// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1i6nFN7v-Cr1c29N9fC04HW3Dwv5-O2Y',
    appId: '1:136938610948:web:c7aa923df3cb4b0e263051',
    messagingSenderId: '136938610948',
    projectId: 'todo-af096',
    authDomain: 'todo-af096.firebaseapp.com',
    storageBucket: 'todo-af096.appspot.com',
    measurementId: 'G-9HL05SLL3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-_b6d8ksH6OAj6sx2EmA88W99_t2CYmo',
    appId: '1:136938610948:android:f43962b3d809670b263051',
    messagingSenderId: '136938610948',
    projectId: 'todo-af096',
    storageBucket: 'todo-af096.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_2r78V4JTy_gyOoHEnnx4jTN06GzO8h4',
    appId: '1:136938610948:ios:3eb1a036786297da263051',
    messagingSenderId: '136938610948',
    projectId: 'todo-af096',
    storageBucket: 'todo-af096.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_2r78V4JTy_gyOoHEnnx4jTN06GzO8h4',
    appId: '1:136938610948:ios:3eb1a036786297da263051',
    messagingSenderId: '136938610948',
    projectId: 'todo-af096',
    storageBucket: 'todo-af096.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1i6nFN7v-Cr1c29N9fC04HW3Dwv5-O2Y',
    appId: '1:136938610948:web:63ea45bf5ac965b8263051',
    messagingSenderId: '136938610948',
    projectId: 'todo-af096',
    authDomain: 'todo-af096.firebaseapp.com',
    storageBucket: 'todo-af096.appspot.com',
    measurementId: 'G-C4H3T093LM',
  );
}
